[build]

  # Directory of Built Files

  publish = "build/"

  # Production Build Command

  command = "CI= npm run build"

[[redirects]]

  # For React Router

  from = "/*"
  to = "/index.html"
  status = 200